name: "DiplomSerega CiCd Prod"
on:
  push:
    branches: ["Prod"]
    
jobs:
  deploy:
    name: Deploy DiplomSerega Prod
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
            cd ${{ secrets.PROJECT_FOLDER }};
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S git checkout Prod;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S git pull;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S docker-compose --file docker-compose.prod.yml down;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S docker-compose --file docker-compose.prod.yml up -d --build;
            echo ${{ secrets.SECRET_PHRASE }} | sudo -S docker system prune --all --force;
